start_p2p_livestream:
  name: Start Live Stream over P2P
  description: Send start live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_sdk

stop_p2p_livestream:
  name: Stop Live Stream over P2P
  description: Send stop live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_sdk

start_rtsp_livestream:
  name: Start Live Stream over RTSP
  description: Enable the camera native RTSP stream and start it in Home Assistant
  target:
    entity:
      domain: camera
      integration: eufy_sdk

stop_rtsp_livestream:
  name: Stop Live Stream over RTSP
  description: Stop the Home Assistant stream and disable the camera native RTSP stream
  target:
    entity:
      domain: camera
      integration: eufy_sdk
